// <auto-generated />
using AcmeAdmin.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcmeAdmin.Api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileAvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileBio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileJoinedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "u-admin",
                            Email = "mahad@acme.pk",
                            EmployeeId = "e1",
                            Name = "Mahad Shehzad",
                            Password = "admin123",
                            ProfileAvatarUrl = "",
                            ProfileBio = "Oversees platform administration and tenant onboarding across all regions.",
                            ProfileDepartment = "Operations",
                            ProfileJoinedAt = "March 2023",
                            ProfileLocation = "Sialkot, Pakistan",
                            ProfilePhone = "+92 300 1234567",
                            ProfileTitle = "Head of Operations",
                            Role = "Admin",
                            TenantIds = "orient,packages,systems"
                        },
                        new
                        {
                            Id = "u-manager",
                            Email = "bilal.ahmed@acme.pk",
                            EmployeeId = "e2",
                            Name = "Bilal Ahmed",
                            Password = "manager123",
                            ProfileAvatarUrl = "",
                            ProfileBio = "Leads the northern sales team and owns the active project portfolio.",
                            ProfileDepartment = "Sales",
                            ProfileJoinedAt = "August 2023",
                            ProfileLocation = "Lahore, Pakistan",
                            ProfilePhone = "+92 321 7654321",
                            ProfileTitle = "Sales Manager",
                            Role = "Manager",
                            TenantIds = "orient,packages"
                        },
                        new
                        {
                            Id = "u-employee",
                            Email = "imran.yousaf@acme.pk",
                            EmployeeId = "e4",
                            Name = "Imran Yousaf",
                            Password = "employee123",
                            ProfileAvatarUrl = "",
                            ProfileBio = "Builds and maintains internal tools for the operations team.",
                            ProfileDepartment = "Engineering",
                            ProfileJoinedAt = "February 2024",
                            ProfileLocation = "Lahore, Pakistan",
                            ProfilePhone = "+92 345 2223344",
                            ProfileTitle = "Software Engineer",
                            Role = "Employee",
                            TenantIds = "orient"
                        },
                        new
                        {
                            Id = "u-viewer",
                            Email = "sana.malik@acme.pk",
                            EmployeeId = "e3",
                            Name = "Sana Malik",
                            Password = "viewer123",
                            ProfileAvatarUrl = "",
                            ProfileBio = "Reviews dashboards and report summaries to support planning decisions.",
                            ProfileDepartment = "Analytics",
                            ProfileJoinedAt = "January 2024",
                            ProfileLocation = "Islamabad, Pakistan",
                            ProfilePhone = "+92 333 9876543",
                            ProfileTitle = "Business Analyst",
                            Role = "Viewer",
                            TenantIds = "orient"
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.AttendanceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClockIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClockOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attendance");

                    b.HasData(
                        new
                        {
                            Id = "e4-att-0",
                            ClockIn = "09:05",
                            ClockOut = "17:35",
                            Date = "2026-09-01",
                            EmployeeId = "e4",
                            Hours = 8.5,
                            Status = "Present"
                        },
                        new
                        {
                            Id = "e4-att-1",
                            ClockIn = "09:00",
                            ClockOut = "17:10",
                            Date = "2026-09-02",
                            EmployeeId = "e4",
                            Hours = 8.1999999999999993,
                            Status = "Present"
                        },
                        new
                        {
                            Id = "e4-att-2",
                            ClockIn = "—",
                            ClockOut = "—",
                            Date = "2026-09-03",
                            EmployeeId = "e4",
                            Hours = 8.0,
                            Status = "Remote"
                        },
                        new
                        {
                            Id = "e4-att-3",
                            ClockIn = "09:20",
                            ClockOut = "17:40",
                            Date = "2026-09-04",
                            EmployeeId = "e4",
                            Hours = 8.3000000000000007,
                            Status = "Present"
                        },
                        new
                        {
                            Id = "e4-att-4",
                            ClockIn = "—",
                            ClockOut = "—",
                            Date = "2026-09-05",
                            EmployeeId = "e4",
                            Hours = 0.0,
                            Status = "Leave"
                        },
                        new
                        {
                            Id = "e4-att-5",
                            ClockIn = "08:55",
                            ClockOut = "17:25",
                            Date = "2026-09-08",
                            EmployeeId = "e4",
                            Hours = 8.5,
                            Status = "Present"
                        },
                        new
                        {
                            Id = "e7-att-0",
                            ClockIn = "09:05",
                            ClockOut = "17:35",
                            Date = "2026-09-01",
                            EmployeeId = "e7",
                            Hours = 8.5,
                            Status = "Present"
                        },
                        new
                        {
                            Id = "e7-att-1",
                            ClockIn = "09:00",
                            ClockOut = "17:10",
                            Date = "2026-09-02",
                            EmployeeId = "e7",
                            Hours = 8.1999999999999993,
                            Status = "Present"
                        },
                        new
                        {
                            Id = "e7-att-2",
                            ClockIn = "—",
                            ClockOut = "—",
                            Date = "2026-09-03",
                            EmployeeId = "e7",
                            Hours = 8.0,
                            Status = "Remote"
                        },
                        new
                        {
                            Id = "e7-att-3",
                            ClockIn = "09:20",
                            ClockOut = "17:40",
                            Date = "2026-09-04",
                            EmployeeId = "e7",
                            Hours = 8.3000000000000007,
                            Status = "Present"
                        },
                        new
                        {
                            Id = "e7-att-4",
                            ClockIn = "—",
                            ClockOut = "—",
                            Date = "2026-09-05",
                            EmployeeId = "e7",
                            Hours = 0.0,
                            Status = "Leave"
                        },
                        new
                        {
                            Id = "e7-att-5",
                            ClockIn = "08:55",
                            ClockOut = "17:25",
                            Date = "2026-09-08",
                            EmployeeId = "e7",
                            Hours = 8.5,
                            Status = "Present"
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = "dept-ops",
                            Lead = "Mahad Shehzad",
                            Name = "Operations",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "dept-sales",
                            Lead = "Bilal Ahmed",
                            Name = "Sales",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "dept-eng",
                            Lead = "Hassan Raza",
                            Name = "Engineering",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "dept-analytics",
                            Lead = "Sana Malik",
                            Name = "Analytics",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "dept-hr",
                            Lead = "Maryam Nawaz",
                            Name = "Human Resources",
                            TenantId = "orient"
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "e1",
                            DepartmentId = "dept-ops",
                            Email = "mahad@acme.pk",
                            JoinedAt = "2023-03-06",
                            Location = "Sialkot",
                            Name = "Mahad Shehzad",
                            Phone = "+92 300 1234567",
                            Position = "Head of Operations",
                            Role = "Admin",
                            Salary = 720000,
                            Status = "Active",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e2",
                            DepartmentId = "dept-sales",
                            Email = "bilal.ahmed@acme.pk",
                            JoinedAt = "2023-08-14",
                            Location = "Lahore",
                            ManagerId = "e1",
                            Name = "Bilal Ahmed",
                            Phone = "+92 321 7654321",
                            Position = "Sales Manager",
                            Role = "Manager",
                            Salary = 480000,
                            Status = "Active",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e3",
                            DepartmentId = "dept-analytics",
                            Email = "sana.malik@acme.pk",
                            JoinedAt = "2024-01-09",
                            Location = "Islamabad",
                            ManagerId = "e2",
                            Name = "Sana Malik",
                            Phone = "+92 333 9876543",
                            Position = "Business Analyst",
                            Role = "Viewer",
                            Salary = 260000,
                            Status = "Active",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e4",
                            DepartmentId = "dept-eng",
                            Email = "imran.yousaf@acme.pk",
                            JoinedAt = "2024-02-01",
                            Location = "Lahore",
                            ManagerId = "e2",
                            Name = "Imran Yousaf",
                            Phone = "+92 345 2223344",
                            Position = "Software Engineer",
                            Role = "Employee",
                            Salary = 340000,
                            Status = "Active",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e5",
                            DepartmentId = "dept-sales",
                            Email = "fatima.sheikh@acme.pk",
                            JoinedAt = "2024-06-18",
                            Location = "Lahore",
                            ManagerId = "e2",
                            Name = "Fatima Sheikh",
                            Phone = "+92 300 4455667",
                            Position = "Sales Executive",
                            Role = "Employee",
                            Salary = 220000,
                            Status = "Invited",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e6",
                            DepartmentId = "dept-ops",
                            Email = "usman.raza@acme.pk",
                            JoinedAt = "2023-11-02",
                            Location = "Karachi",
                            ManagerId = "e1",
                            Name = "Usman Raza",
                            Phone = "+92 301 5566778",
                            Position = "Operations Analyst",
                            Role = "Employee",
                            Salary = 300000,
                            Status = "Active",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e7",
                            DepartmentId = "dept-eng",
                            Email = "zainab.iqbal@acme.pk",
                            JoinedAt = "2024-03-21",
                            Location = "Remote",
                            ManagerId = "e2",
                            Name = "Zainab Iqbal",
                            Phone = "+92 302 6677889",
                            Position = "Frontend Engineer",
                            Role = "Employee",
                            Salary = 320000,
                            Status = "Active",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e8",
                            DepartmentId = "dept-ops",
                            Email = "hamza.farooq@acme.pk",
                            JoinedAt = "2023-09-11",
                            Location = "Karachi",
                            ManagerId = "e1",
                            Name = "Hamza Farooq",
                            Phone = "+92 303 7788990",
                            Position = "Support Specialist",
                            Role = "Employee",
                            Salary = 210000,
                            Status = "Suspended",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e9",
                            DepartmentId = "dept-hr",
                            Email = "maryam.nawaz@acme.pk",
                            JoinedAt = "2023-05-30",
                            Location = "Islamabad",
                            ManagerId = "e1",
                            Name = "Maryam Nawaz",
                            Phone = "+92 304 8899001",
                            Position = "HR Business Partner",
                            Role = "Manager",
                            Salary = 440000,
                            Status = "Active",
                            TenantId = "orient"
                        },
                        new
                        {
                            Id = "e10",
                            DepartmentId = "dept-analytics",
                            Email = "ali.hassan@acme.pk",
                            JoinedAt = "2024-04-15",
                            Location = "Lahore",
                            ManagerId = "e2",
                            Name = "Ali Hassan",
                            Phone = "+92 305 9900112",
                            Position = "Data Analyst",
                            Role = "Employee",
                            Salary = 280000,
                            Status = "Active",
                            TenantId = "orient"
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.LeaveRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = "l1",
                            Days = 3,
                            EmployeeId = "e4",
                            From = "2026-09-22",
                            Reason = "Family trip",
                            Status = "Pending",
                            To = "2026-09-24",
                            Type = "Annual"
                        },
                        new
                        {
                            Id = "l2",
                            Days = 1,
                            EmployeeId = "e4",
                            From = "2026-08-11",
                            Reason = "Fever",
                            Status = "Approved",
                            To = "2026-08-11",
                            Type = "Sick"
                        },
                        new
                        {
                            Id = "l3",
                            Days = 1,
                            EmployeeId = "e7",
                            From = "2026-09-18",
                            Reason = "Personal errand",
                            Status = "Pending",
                            To = "2026-09-18",
                            Type = "Casual"
                        },
                        new
                        {
                            Id = "l4",
                            Days = 3,
                            EmployeeId = "e10",
                            From = "2026-10-01",
                            Reason = "Vacation",
                            Status = "Pending",
                            To = "2026-10-03",
                            Type = "Annual"
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.Meeting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Attendees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMins")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = "m1",
                            Attendees = "Mahad, Bilal, Maryam",
                            Date = "2026-09-10",
                            DurationMins = 45,
                            OwnerId = "u-admin",
                            Status = "Scheduled",
                            Time = "10:00",
                            Title = "Weekly leadership sync"
                        },
                        new
                        {
                            Id = "m2",
                            Attendees = "Mahad, Maryam",
                            Date = "2026-09-12",
                            DurationMins = 60,
                            OwnerId = "u-admin",
                            Status = "Scheduled",
                            Time = "14:30",
                            Title = "Q4 hiring plan review"
                        },
                        new
                        {
                            Id = "m3",
                            Attendees = "Mahad, External",
                            Date = "2026-09-05",
                            DurationMins = 30,
                            OwnerId = "u-admin",
                            Status = "Completed",
                            Time = "16:00",
                            Title = "Vendor contract call"
                        },
                        new
                        {
                            Id = "m4",
                            Attendees = "Bilal, Fatima, Ali",
                            Date = "2026-09-09",
                            DurationMins = 20,
                            OwnerId = "u-manager",
                            Status = "Scheduled",
                            Time = "09:15",
                            Title = "Sales pipeline standup"
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.Payslip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Deductions")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gross")
                        .HasColumnType("int");

                    b.Property<int>("Net")
                        .HasColumnType("int");

                    b.Property<string>("PaidOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tax")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payslips");

                    b.HasData(
                        new
                        {
                            Id = "e4-pay-0",
                            Deductions = 3500,
                            EmployeeId = "e4",
                            Gross = 78000,
                            Net = 66700,
                            PaidOn = "2026-06-30",
                            Period = "June 2026",
                            Tax = 7800
                        },
                        new
                        {
                            Id = "e4-pay-1",
                            Deductions = 3500,
                            EmployeeId = "e4",
                            Gross = 78000,
                            Net = 66700,
                            PaidOn = "2026-07-31",
                            Period = "July 2026",
                            Tax = 7800
                        },
                        new
                        {
                            Id = "e4-pay-2",
                            Deductions = 3500,
                            EmployeeId = "e4",
                            Gross = 78000,
                            Net = 66700,
                            PaidOn = "2026-08-31",
                            Period = "August 2026",
                            Tax = 7800
                        },
                        new
                        {
                            Id = "e7-pay-0",
                            Deductions = 3500,
                            EmployeeId = "e7",
                            Gross = 74000,
                            Net = 63100,
                            PaidOn = "2026-06-30",
                            Period = "June 2026",
                            Tax = 7400
                        },
                        new
                        {
                            Id = "e7-pay-1",
                            Deductions = 3500,
                            EmployeeId = "e7",
                            Gross = 74000,
                            Net = 63100,
                            PaidOn = "2026-07-31",
                            Period = "July 2026",
                            Tax = 7400
                        },
                        new
                        {
                            Id = "e7-pay-2",
                            Deductions = 3500,
                            EmployeeId = "e7",
                            Gross = 74000,
                            Net = 63100,
                            PaidOn = "2026-08-31",
                            Period = "August 2026",
                            Tax = 7400
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "p1",
                            Client = "Orient Retail",
                            DueDate = "2026-11-15",
                            LeadId = "e2",
                            MemberIds = "e4,e7,e10",
                            Name = "Retail portal revamp",
                            Progress = 62,
                            Status = "In progress"
                        },
                        new
                        {
                            Id = "p2",
                            Client = "Internal Ops",
                            DueDate = "2027-01-20",
                            LeadId = "e2",
                            MemberIds = "e6,e4",
                            Name = "Warehouse automation",
                            Progress = 15,
                            Status = "Planning"
                        },
                        new
                        {
                            Id = "p3",
                            Client = "Internal",
                            DueDate = "2026-12-05",
                            LeadId = "e2",
                            MemberIds = "e3,e10",
                            Name = "Analytics data mart",
                            Progress = 40,
                            Status = "On hold"
                        });
                });

            modelBuilder.Entity("AcmeAdmin.Api.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrandingPrimary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandingShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnabledFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = "orient",
                            BrandingPrimary = "#a9805b",
                            BrandingShortName = "OT",
                            EnabledFeatures = "dashboard,users,reports,settings",
                            Name = "Orient Textiles"
                        },
                        new
                        {
                            Id = "packages",
                            BrandingPrimary = "#8f6844",
                            BrandingShortName = "PG",
                            EnabledFeatures = "dashboard,users,settings",
                            Name = "Packages Group"
                        },
                        new
                        {
                            Id = "systems",
                            BrandingPrimary = "#7c5234",
                            BrandingShortName = "SL",
                            EnabledFeatures = "dashboard,reports",
                            Name = "Systems Limited"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
